# Generated by Django 2.1.7 on 2019-03-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190317_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Product in Order', 'verbose_name_plural': 'Products in Order'},
        ),
    ]
